name: 'Automated Lambda Proxy Integration'
description: 'Deploy functions to AWS Lambda and configure proxy integrations.'
inputs:
  parentId:
    description: 'The ID of the root path resource in API Gateway.'
    required: true
  apiId: 
    description: 'The ID of the API Gateway API to configure endpoints.'
    required: true
  env:
    desription: 'The development environment to deploy to.'
    required: true
outputs: 
  arns:
    description: 'The updated Lambda function ARNs'
runs:
  using: 'node12'
  main: 'dist/index.js'
